version: '3.3'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    volumes:
      - /Users/regis/workspace/keycloak/docker:/tmp/
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      KEYCLOAK_USER: regis
      KEYCLOAK_PASSWORD: regis
      DB_PORT: 3306
      DB_DATABASE: kc_database
      DB_USER: kc_user_db
      DB_PASSWORD: kc_pwd_db
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    depends_on:
      - mysql
    networks:
      - kc-net
    ports:
      - 8090:8080

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: kc_database
      MYSQL_USER: kc_user_db
      MYSQL_PASSWORD: kc_pwd_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - kc-net

volumes:
  my-db: null

networks:
  kc-net:
    driver: bridge