version: '3.3'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: regis
      KEYCLOAK_PASSWORD: regis
      DB_PORT: 3306
      DB_DATABASE: kc_database
      DB_USER: kc_user_db
      DB_PASSWORD: kc_pwd_db
    networks:
      - kc-net
    ports:
      - 8090:8080

  mysql:
    container_name: mysql_kc
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: kc_database
      MYSQL_USER: kc_user_db
      MYSQL_PASSWORD: kc_pwd_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - kc-net

volumes:
  my-db: null

networks:
  kc-net:
    driver: bridge